<a href="https://colab.research.google.com/github/AG-0745/UCS420/blob/main/Cognitive_Ass_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Q1

In [49]:
temperature=np.array([25,28,31,35,38,27,33,40])
print(temperature+2)
print((9/5)*temperature+32)
print(temperature[temperature>32])
print(np.sum(temperature>32))

[27 30 33 37 40 29 35 42]
[ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
[35 38 33 40]
4


Q2

In [50]:
steps=np.array([
[5000,6200,7100],
[8000,7500,9000],
[4500,5100,4800],
[9000,8500,9500]])
print(f"Total: {np.sum(steps)}")
print(f"Mean: {np.mean(steps)}")
print(f"Max: {np.max(steps)} Min: {np.min(steps)}")
print(f"Per day: {np.sum(steps,axis=0)}")
print(f"Per user: {np.sum(steps,axis=1)}")
print(f"Max position (user,day): {np.unravel_index(np.argmax(steps),steps.shape)}")

Total: 84200
Mean: 7016.666666666667
Max: 9500 Min: 4500
Per day: [26500 27300 30400]
Per user: [18300 24500 14400 27000]
Max position (user,day): (np.int64(3), np.int64(2))


Q3

In [51]:
original=np.array([1,2,3,4,5,6])
subset=original[1:5]
print(subset)
subset[0]=999
print(original)
print(subset)

subset_copy=original[1:5].copy()
subset_copy[0]=500
print(original)
print(subset_copy)

matrix=np.arange(1,13).reshape(3,4)
print(matrix)
print(matrix[0])
print(matrix[-1])
print(matrix[:,1])
print(matrix[1:3,2:4])

flattened=matrix.flatten()
raveled=matrix.ravel()
print(flattened)
print(raveled)

raveled[0]=100
print(matrix)
print(raveled)
#ravel() returns a view where possible so changing it also changes the original matrix

flattened[0]=200
print(matrix)
print(flattened)
#flatten() always returns a copy so the original matrix is unaffected

print(f"shape: {matrix.shape} ndim: {matrix.ndim} size: {matrix.size} dtype: {matrix.dtype}")

[2 3 4 5]
[  1 999   3   4   5   6]
[999   3   4   5]
[  1 999   3   4   5   6]
[500   3   4   5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[ 7  8]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[200   2   3   4   5   6   7   8   9  10  11  12]
shape: (3, 4) ndim: 2 size: 12 dtype: int64


Q4

In [52]:
X=np.array([
[6,70,3],
[5,50,6],
[8,80,2],
[4,30,8]
])
y=np.array([40,65,30,85])
print(f"shape: {X.shape} ndim: {X.ndim}")

X_transpose=X.T
print(X_transpose)

XtX=X.T@X
print(XtX)
XtX_inv=np.linalg.inv(XtX)
print(XtX_inv)

beta=XtX_inv@X.T@y
print(beta)

new_user=np.array([5,40,7])
print(new_user@beta)

shape: (4, 3) ndim: 2
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
[-0.15921454  0.14083853 10.06302242]
75.27862544779117
