<a href="https://colab.research.google.com/github/AG-0745/UCS420/blob/main/Cognitive_Ass_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

Q1

In [6]:
arr=np.array([1,2,3,4,5])
print(arr+2)
print(arr*3)
print(arr/2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Q2

In [7]:
arr2=np.array([1,2,3,6,4,5])
print(arr2[::-1])

x=np.array([1,2,3,4,5,1,2,1,1,1])
values,counts=np.unique(x,return_counts=True)
most_frequent_x=values[np.argmax(counts)]
print(most_frequent_x,np.where(x==most_frequent_x)[0])

y=np.array([1,1,1,2,3,4,2,4,3,3])
values_y,counts_y=np.unique(y,return_counts=True)
most_frequent_y=values_y[np.argmax(counts_y)]
print(most_frequent_y,np.where(y==most_frequent_y)[0])

[5 4 6 3 2 1]
1 [0 5 7 8 9]
1 [0 1 2]


Q3

In [8]:
arr3=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr3[0,1])
print(arr3[2,0])

20
70


Q4

In [16]:
anirudh_garg=np.linspace(10,100,25)
print(anirudh_garg)
print(f"ndim: {anirudh_garg.ndim}")
print(f"shape: {anirudh_garg.shape}")
print(f"size: {anirudh_garg.size}")
print(f"dtype: {anirudh_garg.dtype}")
print(f"nbytes: {anirudh_garg.nbytes}")

anirudh_garg_transpose=anirudh_garg.reshape(25,1)
print(anirudh_garg_transpose)
print(anirudh_garg.T)
#T has no visible effect on a 1D array since transpose only swaps axes and there is only one axis, reshape(25,1) is what actually turns it into a column vector

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
ndim: 1
shape: (25,)
size: 25
dtype: float64
nbytes: 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5

In [23]:
ucs420_anirudh_garg=np.array([10,20,30,40,50,60,70,80,90,15,20,35]).reshape(3,4)
print(ucs420_anirudh_garg)
print(f"mean: {np.mean(ucs420_anirudh_garg)}")
print(f"median: {np.median(ucs420_anirudh_garg)}")
print(f"max: {np.max(ucs420_anirudh_garg)}")
print(f"min: {np.min(ucs420_anirudh_garg)}")
print(f"unique: {np.unique(ucs420_anirudh_garg)}")

reshaped_ucs420_anirudh_garg=ucs420_anirudh_garg.reshape(4,3)
print(reshaped_ucs420_anirudh_garg)

resized_ucs420_anirudh_garg=np.resize(ucs420_anirudh_garg,(2,3))
print(resized_ucs420_anirudh_garg)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
mean: 43.333333333333336
median: 37.5
max: 90
min: 10
unique: [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
